spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: Department-Service
          uri: lb://Department-Service
          predicates:
            - Path=/Department/**
          filters:
            - name: Hystrix
              args:
               name: fallbackCommand
               fallbackuri: forward:/departmentfallback
          
server:
  port : 8877

management:
  endpoints:
    web:
      exposure:
        include: "*"

